### PR TITLE
Begin iterating

### PR DESCRIPTION
**Pull request by Keyrxng**
Should an issue be opened or just iterate through PR discussion @0x4007?

- added a few basic tests
- split the codebase into three focus areas
- implemented salts for key derivation
- mnemonics for recovery
- code comments and quotes from the docs

<hr/>

I'm putting a focus on the key generation process first as that's the foundation of all of this. So with that said, the future plans of incorporating a `Sign in with GitHub` option would be a leap in enhancing the security of the process and I think should be integrated from the jump

It adds more MFA checkpoints and allows us to use data points from unrelated sources specific to the user which is far less publicly available increasing our fault tolerance. It does add slight friction towards the goal of making it a seamless 'no loading screen' UX

<hr/>

A notable change is salts:
- I think that a single org salt is a bad idea but the org could have a salt which itself is a mnemonic of 24 words. They'd be used in rotation according to some defined metric/algo or just randomly chosen
- This increases the security of the process and so long as the org salts are secure then it only slightly increases the difficulty for recovery for us
- I think that converting our data points into words via some algo (I've implemented a rudimentary approach) and then using that mnemonic to derive our key is a good approach

<hr/>

I've only tested in a node env so far but have made adjustments to the webauthn logic such a create and request. 

Looking at the fp pkg readme it's 40-60% accurate and can't distinguish between two identical instances so while that is a good approach I don't think it's as reliable as we need it to be unless the premium route is taken with that but the alternative sounds like KYC, rock and a hard place.

If we integrate that as a core data point and it gets it wrong our key derivation will be all wrong which is what I'm concerned about.

### CODE REVIEW

**Comment by Keyrxng** [comment]
Jest CI didn't run here but ran against `development` and failed.

I noticed that `ethers` is `v6` and not `v5` coming from `ts-template` so are we slowly migrating to `v6` everywhere?

image

**Comment by 0x4007** [comment]
> Should an issue be opened or just iterate through PR discussion @0x4007?

Generally speaking, implementation is more useful than ideas, so it's appreciated that you iterate over pull requests (at risk of implementing something that doesn't align with the vision, in exchange for conducting further research and bringing more information to the discussion.) Both are okay though. 

> * added a few basic tests
> * split the codebase into three focus areas

Great!

> * implemented salts for key derivation
> * mnemonics for recovery

Don't think we should do this. 

> * code comments and quotes from the docs
> 
> I'm putting a focus on the key generation process first as that's the foundation of all of this. So with that said, the future plans of incorporating a `Sign in with GitHub` option would be a leap in enhancing the security of the process and I think should be integrated from the jump

"Sign in with GitHub" should be used only to manage the associated SAFE. This should be in a separate app. 

> It adds more MFA checkpoints and allows us to use data points from unrelated sources specific to the user which is far less publicly available increasing our fault tolerance. It does add slight friction towards the goal of making it a seamless 'no loading screen' UX

I appreciate the work you've done for enhancing the security around key generation, but fundamentally, I think you should look at this project from a different lens. 

- These signing keys are intended to claim permits to the SAFE (not the client-side signer.) 
- Permit beneficiaries can not be modified. They can only go to the SAFE.
- These signing keys are not intended to hold any monetary value. 
- They also don't need any gas fees to be paid, due to the Gnosis Chain sponsored transactions feature. 
- The UX should be the top priority and we can work backwards to making it secure in case we want to extend the vision and capabilities of these client-side signers. 
- If we decentralize the deterministic key generation with device fingerprints, assuming those are difficult to brute force (I'm actually not sure if they are) then it should be secure enough as is. This is especially attractive to me if we don't let users export the private key, and instead consider them disposable signers for the SAFE (the "real" wallet.)  

> Looking at the fp pkg readme it's 40-60% accurate and can't distinguish between two identical instances 

Can you cite your source? They built a business on this tech so its difficult to believe that its only ~50% accurate. I also don't know what you mean by "can't distinguish between two identical instances"

---

Ethers is v5 because ChatGPT was relying on methods only available in v5 for the generated code. 

--- 

"Delete, delete, delete. If you don't end up reintroducing 10% of what you delete, you didn't cut enough." - Elon Musk

Let's focus on good UX and leave out the speculative "what if" capabilities.

**Comment by 0x4007** [comment]
Sorry, introduced some merge conflicts @Keyrxng

**Comment by Keyrxng** [comment]
> Can you cite your source?

- https://github.com/fingerprintjs/fingerprintjs?tab=readme-ov-file#accuracy

Okay taking onboard everything you have said I think then that I'll focus on ensuring that the first three bullet points hold true then I think what you are suggesting is that based on the credential and fp alone we'd be able to generate these 'throwaway signers' which should only be able to instantly claim the permit into the SAFE. So focus on the SAFE area first and build out keygen more later.

Is this intended to be it's own distinct UI or will this be a package to be used where we need it?

<hr/>

I was trying to look for more info on what txs get sponsored but I can't find what I'm looking for. Do you know if it's only sponsored gas/token transfers or is it any on-chain transaction calling any contract, any method?

<hr/>

About the conflicts, `package.json` has `Ethers@v6` but the conflict is just adding a ts-ignore. Does `Ethers@v6` still have `.utils` it's just not recognized? <del>Interesting</del> Not had enough coffee yet

**Comment by Keyrxng** [comment]
@gentlementlegen should we be committing the `test-dashboard.md`?

**Comment by gentlementlegen** [comment]
@Keyrxng No, this is auto-generated and only used for the Action output summary. For example: https://github.com/Meniole/ts-template/actions/runs/9617961749
You can add it to `.gitignore` if you want.

**Comment by 0x4007** [comment]
> > Can you cite your source?
> 
> * https://github.com/fingerprintjs/fingerprintjs?tab=readme-ov-file#accuracy

Okay, then I imagine we will need a very fast UX flow to be able to add a new "device key" to one's SAFE (aka a generated EVM public address.) I imagine that with regular iOS updates every few weeks or so, that the device fingerprint may change. 

In this case, it could be interesting to save it in a cookie, or a query param, and read from that value on a dedicated "add device key" app/UI. 

I am very keen on isolating these tools into small and separate codebases instead of trying to make a single complex one. This approach with simple UIs is significantly faster for us to ship and maintain. This is one of several reasons why I am against using frameworks like React etc. Its heavy bloat in the context of this strategy. 

> 
> Okay taking onboard everything you have said I think then that I'll focus on ensuring that the first three bullet points hold true then I think what you are suggesting is that based on the credential and fp alone we'd be able to generate these 'throwaway signers' which should only be able to instantly claim the permit into the SAFE. So focus on the SAFE area first and build out keygen more later.

Could be worthwhile to [make a separate repository](https://github.com/ubiquity/safe.ubq.fi) for the SAFE management UI. We should associate a GitHub login with a SAFE there. I don't have the entire tech stack or flow clear in my mind, but in the context of permit claims, ideally we should achieve the following:

1. No more wallet registration required. Instead we should be able to easily allow users to deploy a SAFE on Gnosis Chain, associate it with their GitHub user ID, and automatically use that as the beneficiary for payments. 
2. Deterministic client-side EVM private key generation: so that we no longer have to use MetaMask etc and have instant performance with an in-app signing key. This key should be able to claim permits on behalf of the user's SAFE, and do so using Gnosis Chain sponsored transactions. 
3. Fully abstract away the crypto wallet concepts. If we can get by without exposing any private keys, or public addresses to our users, then we did a really great job. 

> 
> Is this intended to be it's own distinct UI or will this be a package to be used where we need it?

The new repository I created is now hosted at safe.ubq.fi.

> I was trying to look for more info on what txs get sponsored but I can't find what I'm looking for. Do you know if it's only sponsored gas/token transfers or is it any on-chain transaction calling any contract, any method?

Try making a SAFE on Gnosis Chain using https://app.safe.global/new-safe/create at the end you will notice that you can have your transaction sponsored by Gnosis. 

> About the conflicts, `package.json` has `Ethers@v6` but the conflict is just adding a ts-ignore. Does `Ethers@v6` still have `.utils` it's just not recognized? ~Interesting~ Not had enough coffee yet

**Comment by 0x4007** [comment]
Perhaps we can merge this to another branch?

**Comment by Keyrxng** [comment]
- https://www.github.com/safe-global/safe-core-sdk/pull/808 looks like safe have added passkey support but it's not been released yet but that should streamline things for setting up/adding to SAFEs with passkeys

I'm thinking if SAFE feel it's secure enough to use just the credential to facilitate setting up and control of SAFEs then is fingerprinting necessary do you think? Essentially we'd just be streamlining the creation of SAFEs for our users, we may not even have to derive a PK at all given that deployment is free (at least for now). Although I think this means that 'throw away signer' is not longer possible as they'd be accessing their safe directly with the passkey. 

Either way it's probs better to wait till that PR goes through what do you think?

> Try making a SAFE on Gnosis Chain using https://app.safe.global/new-safe/create at the end you will notice that you can have your transaction sponsored by Gnosis.

I checked it out and it seems like it's any tx doesn't it, v handy indeed.

<hr/>

I'll work between this and https://github.com/ubiquity/safe.ubq.fi while I still have a few larger PRs open

**Comment by 0x4007** [comment]
My original idea was to do that, but I figured that fingerprinting might be more streamlined at the cost of security. For permits it could make sense, but if we want one solution to work for everything, then maybe back to the original idea of webauthn. I'm not 100% sure.

**Pull request merged**
